TOKEN = '5751024125:AAFHkyBrgab3LVI_OpmmpHoyhw-ts2Dqlo4'

admin_ids: list[int] = [828900493]

photos = ['AgACAgIAAxkBAAIOZGUIYHlaUfqLfAMqpDKzc1p6ubYEAAIy2TEbXpxASEpGIVE_eqQjAQADAgADcwADMAQ',
          'AgACAgIAAxkBAAIOZmUIYKQmxohqvWwXlLzmgUiT4zbxAAI72TEbXpxASEYH1sz_b1wEAQADAgADcwADMAQ']

audios = ['CQACAgIAAxkBAAIOcWUIYjXRYETW7IeU0nzEKpcnyiV9AALSNgACXpxASNZq7NGIOnvzMAQ',
          'CQACAgIAAxkBAAIOc2UIYmjJBLBCmVuE90X4QI8VpdudAALUNgACXpxASLzV-SBOzaV-MAQ']

documents = ['BQACAgIAAxkBAAIOdmUIYszV49nD--fzDtsIxfeSC5JMAALaNgACXpxASBJgHZq0HiAlMAQ',
             'BQACAgIAAxkBAAIOeGUIY1Sj5ZcoW_hpxnGaaiscfxstAALhNgACXpxASEZAjCAEWXWGMAQ']

videos = ['BAACAgIAAxkBAAIOemUIY4uHhAWFtrzkLfjz2maRfaqdAALjNgACXpxASEJ8kZzfwPDiMAQ',
          'BAACAgIAAxkBAAIOfGUIY7LFG1V0oB2wkLo_jymXg4vRAALoNgACXpxASPWXTaZbSRYGMAQ']

voices = ['AwACAgIAAxkBAAIObGUIYXq__J5aO-Wn-aW4t0tr-9FUAALMNgACXpxASGlb4IhXuZ2zMAQ',
          'AwACAgIAAxkBAAIObmUIYZvKpTR-sFyeXZ6ortHD68peAALONgACXpxASBdULBpzzapcMAQ']