name: aiogram_test

services:

  postgres:
    image: postgres:16-alpine
    restart: no
    ports:
      - 127.0.0.1:5432:5432
    environment:
        #TODO: change all names and pass
      - POSTGRES_USER=costa
      - POSTGRES_PASSWORD=datatotest
      - POSTGRES_DB=test_db
    volumes:
      - postgres-test-db:/var/lib/postgresql/test_db

  pgadmin:
    image: dpage/pgadmin4:8.9
    restart: no
    ports:
      - 127.0.0.1:8080:80
    environment:
        #TODO: change email and pass
      - PGADMIN_DEFAULT_EMAIL=a@a.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin
    volumes:
      - pgadmin-test-db:/var/lib/pgadmin
    depends_on:
      - postgres

volumes:
  postgres-test-db:
  pgadmin-test-db:
